// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pokegraf.Persistence.Context;

namespace Pokegraf.Persistence.Migrations
{
    [DbContext(typeof(PokegrafDbContext))]
    [Migration("20191015145644_AddedUserStats")]
    partial class AddedUserStats
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Pokegraf.Domain.Entity.Chat", b =>
                {
                    b.Property<long>("Id");

                    b.Property<DateTime>("FirstSeen");

                    b.Property<string>("Title");

                    b.Property<int>("Type");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("Pokegraf.Domain.Entity.Conversation", b =>
                {
                    b.Property<long>("ChatId");

                    b.Property<int>("UserId");

                    b.HasKey("ChatId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("Pokegraf.Domain.Entity.Stats", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.ToTable("Stats");
                });

            modelBuilder.Entity("Pokegraf.Domain.Entity.User", b =>
                {
                    b.Property<int>("Id");

                    b.Property<DateTime>("FirstSeen");

                    b.Property<bool>("IsBot");

                    b.Property<string>("LanguageCode");

                    b.Property<Guid>("StatsId");

                    b.Property<string>("TrainerName");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.HasIndex("StatsId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Pokegraf.Domain.Entity.Conversation", b =>
                {
                    b.HasOne("Pokegraf.Domain.Entity.Chat", "Chat")
                        .WithMany("Conversations")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Pokegraf.Domain.Entity.User", "User")
                        .WithMany("Conversations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Pokegraf.Domain.Entity.Stats", b =>
                {
                    b.OwnsOne("Pokegraf.Domain.Entity.Stats+RequestStats", "Requests", b1 =>
                        {
                            b1.Property<Guid>("Id");

                            b1.Property<int>("Fusion");

                            b1.Property<int>("Pokemon");

                            b1.HasKey("Id");

                            b1.ToTable("StatsRequests");

                            b1.HasOne("Pokegraf.Domain.Entity.Stats")
                                .WithOne("Requests")
                                .HasForeignKey("Pokegraf.Domain.Entity.Stats+RequestStats", "Id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("Pokegraf.Domain.Entity.User", b =>
                {
                    b.HasOne("Pokegraf.Domain.Entity.Stats", "Stats")
                        .WithOne("User")
                        .HasForeignKey("Pokegraf.Domain.Entity.User", "StatsId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
